### ISSUE TITLE
Illegal instruction generated when building OIDN for Apple M1/M2 (ISPC 1.21.x)

### ISSUE THREAD

**Issue by atafra** [ispc/ispc#2681] opened 2023-10-14 13:33 UTC
ISPC 1.21.x generates illegal instruction(s) when building Intel Open Image Denoise on macOS for ARM64. This is a regression: prior versions, e.g. ISPC 1.20.0, generate correct code.

Steps to reproduce on macOS Sonoma, Xcode 15.0, Apple M1:
```
git clone --recursive https://github.com/OpenImageDenoise/oidn.git
cd oidn
mkdir build
cd build
cmake ..
make -j
./oidnTest
```
This results in the following error:
`zsh: bus error  ./oidnTest`

After rebuilding in Debug mode, the error is more meaningful:
`zsh: illegal hardware instruction  ./oidnTest`

The illegal instruction is in `cpu_image_copy.dev.o`:

<img width="508" alt="Screenshot 2023-10-14 at 16 20 05" src="https://github.com/ispc/ispc/assets/4058111/8f3ca4f5-9f38-4d0d-b70f-19aaae2e73f0">

**Comment by nurmukhametov** [comment] 2023-10-16 10:23
I can't reproduce it, though environment I used is slightly different (macOS 13.5, Xcode 14.3.1, Apple M1).

`oidnTest` works (v2.1.0) and I don't see any illegal instruction or unknown opcodes disassembling `cpu_image_copy.dev.o`.

Is this disassemble listing from `oidnTest` or `cpu_image_copy.dev.o` itself? Which function is it? It would be useful to check objdump of `cpu_image_copy.dev.o` only to understand if this is a pure ISPC issues, or some problem caused by interacting with system toolchain. I suspect the second because the first one has to be reproducible regardless environment.

**Comment by atafra** [comment] 2023-10-16 10:39
The environment is very likely critical to reproduce this issue. I can't reproduce it if I build OIDN on a machine with older Xcode, but I can reproduce it on another M2 Max machine with Xcode 15. So I get the illegal instruction on two different machines, both with Xcode 15. Only the building environment matters: if I copy the correct binary to a machine on which the incorrect binary is produced, it still runs fine.

As I mentioned before, the illegal instruction is inside `cpu_image_copy.dev.o`. There is only one non-inlined function there. The actual instruction comes from an inlined function: https://github.com/OpenImageDenoise/oidn/blob/f448bcef182623c4f76428da15f152e0c5542a15/devices/cpu/image_accessor.isph#L27

**Comment by atafra** [comment] 2023-10-16 13:33
It seems the issue happens only when using the new linker in Xcode 15. Forcing the old linker with `-Wl,-ld_classic` fixes it. The instructions generated by ISPC look correct but are corrupted by the linker.

**Comment by nurmukhametov** [comment] 2023-10-17 15:50
I reproduced that with Xcode 15.

ISPC generated function looks fine until being linked into the shared library by the new Xcode linker. It corrupts or rewrites `fmov x5, d16` to `ucvtf   d5, x16, #10` that doesn't look right. I suggest that it invalidates pointer value that is derefenced soon after.

The reproducer is [here](https://ispc.godbolt.org/z/Mojbeeb4d). Commands to reproduce:

```bash
$ ispc --arch=aarch64 --addressing=64 -O3 --target=neon-i32x8 --woff -o obj.o cpu_image_copy.dev.i
$ ld -dynamic -dylib -arch arm64 -platform_version macos 13.0.0 14.0 obj.o -o lib.dylib
ld: warning: no platform load command found in 'obj.o', assuming: macOS
$ objdump -D lib.dylib | grep ucvtf
    34dc: 9e43e5f1      ucvtf   d17, x15, #7
```

**Comment by cooperp** [comment] 2023-10-27 17:09
I was able to reproduce with Xcode 15.0.  But Xcode 15.1 bets 2 (wikipedia says that is a build number of 15C5042i) no longer reproduces. Please give that a try if you have a chance.

**Comment by pbrubaker** [comment] 2024-04-25 02:02
Closing this issue as @cooperp noted that this is no longer reproducing in Xcode 15.1.  If this is in error please reopen.

**Closed by pbrubaker** 2024-04-25 02:02 UTC
