### ISSUE TITLE
Compile crash on uniform variable

### ISSUE THREAD

**Issue by kvidimce** [ispc/ispc#1393] opened 2019-01-03 14:57 UTC
I've modified one of the included examples to test an idea and I ran into a compiler crash. I was able to trim it down to a pretty simple reproducer:

% ispc --target=generic-x64 --emit-c++ -o bug.cpp bug.ispc
ispc: /usr/local/src/llvm/llvm-5.0/lib/IR/Instructions.cpp:1400: void llvm::StoreInst::AssertOK(): Assertion `getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.
main.cpp(235): FATAL ERROR: Unhandled signal sent to process; terminating.
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
Aborted (core dumped)
% cat bug.cpp
typedef double<3> double3;

struct Triangle {
  double3 v0;
  double3 v1;
  double3 v2;
};

void
intersect_triangle(const uniform Triangle &tri)
{
#define ISPC_SHOW_CRASH
#ifdef ISPC_SHOW_CRASH
  // This crashes ispc
  uniform double3 p0 = tri.v0;
#else
  // This works
  double3 p0 = tri.v0;
#endif

**Comment by kvidimce** [comment] 2019-01-03 15:03
I probably should've included version info. I am using the latest available binary from the ispc web site:

% ispc --version
Intel(r) SPMD Program Compiler (ispc), 1.9.2 (build commit 417b33ee4ab6ef78 @ 20171111, LLVM 5.0)

**Comment by aneshlya** [comment] 2019-01-03 23:06
The problem is already fixed in trunk. Please build ISPC from latest sources.

**Comment by kvidimce** [comment] 2019-01-03 23:07
Confirmed. Thanks. This can be closed.

**Closed** 2019-01-03 23:10 UTC
