### ISSUE TITLE
Build breaks with llvm-70: undefined reference to `llvm::Module::dump() const'

### ISSUE THREAD

**Issue by yurivict** [ispc/ispc#1427] opened 2019-02-22 07:34 UTC
The FreeBSD port fails to build with these messages:
```
clang++70 -O2  -o ispc objs/ast.o objs/builtins.o objs/cbackend.o objs/ctx.o objs/decl.o objs/expr.o objs/func.o objs/ispc.o objs/llvmutil.o objs/main.o objs/module.o objs/opt.o objs/stmt.o objs/sym.o objs/type.o objs/util.o objs/builtins-dispatch.o objs/builtins-target-avx2-i64x4-32bit.o objs/builtins-target-avx11-i64x4-32bit.o objs/builtins-target-avx1-i64x4-32bit.o objs/builtins-target-avx1-32bit.o objs/builtins-target-avx1-x2-32bit.o objs/builtins-target-avx11-32bit.o objs/builtins-target-avx11-x2-32bit.o objs/builtins-target-avx2-32bit.o objs/builtins-target-avx2-x2-32bit.o objs/builtins-target-sse2-32bit.o objs/builtins-target-sse2-x2-32bit.o objs/builtins-target-sse4-8-32bit.o objs/builtins-target-sse4-16-32bit.o objs/builtins-target-sse4-32bit.o objs/builtins-target-sse4-x2-32bit.o objs/builtins-target-generic-4-32bit.o objs/builtins-target-generic-8-32bit.o objs/builtins-target-generic-16-32bit.o objs/builtins-target-generic-32-32bit.o objs/builtins-target-generic-64-32bit.o objs/builtins-target-generic-1-32bit.o objs/builtins-target-knl-32bit.o objs/builtins-target-skx-32bit.o objs/builtins-target-avx2-i64x4-64bit.o objs/builtins-target-avx11-i64x4-64bit.o objs/builtins-target-avx1-i64x4-64bit.o objs/builtins-target-avx1-64bit.o objs/builtins-target-avx1-x2-64bit.o objs/builtins-target-avx11-64bit.o objs/builtins-target-avx11-x2-64bit.o objs/builtins-target-avx2-64bit.o objs/builtins-target-avx2-x2-64bit.o objs/builtins-target-sse2-64bit.o objs/builtins-target-sse2-x2-64bit.o objs/builtins-target-sse4-8-64bit.o objs/builtins-target-sse4-16-64bit.o objs/builtins-target-sse4-64bit.o objs/builtins-target-sse4-x2-64bit.o objs/builtins-target-generic-4-64bit.o objs/builtins-target-generic-8-64bit.o objs/builtins-target-generic-16-64bit.o objs/builtins-target-generic-32-64bit.o objs/builtins-target-generic-64-64bit.o objs/builtins-target-generic-1-64bit.o objs/builtins-target-knl-64bit.o objs/builtins-target-skx-64bit.o objs/builtins-c-32.o objs/builtins-c-64.o objs/stdlib_mask1_ispc.o objs/stdlib_mask8_ispc.o objs/stdlib_mask16_ispc.o objs/stdlib_mask32_ispc.o objs/stdlib_mask64_ispc.o objs/parse.o objs/lex.o -L/usr/local/llvm70/lib  -lclangFrontend -lclangDriver -lclangSerialization -lclangParse -lclangSema -lclangAnalysis -lclangAST -lclangBasic -lclangEdit -lclangLex -lLLVM-7 -lexecinfo -lpthread -lcurses -lz
objs/llvmutil.o: In function `lDumpValue(llvm::Value*, std::__1::set<llvm::Value*, std::__1::less<llvm::Value*>, std::__1::allocator<llvm::Value*> >&)':
llvmutil.cpp:(.text+0x3d60): undefined reference to `llvm::Value::dump() const'
objs/opt.o: In function `Optimize(llvm::Module*, int)':
opt.cpp:(.text+0x173): undefined reference to `llvm::Module::dump() const'
opt.cpp:(.text+0x1527): undefined reference to `llvm::Module::dump() const'
objs/opt.o: In function `IntrinsicsOpt::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text+0x17cc): undefined reference to `llvm::Value::dump() const'
opt.cpp:(.text+0x2257): undefined reference to `llvm::Value::dump() const'
objs/opt.o: In function `InstructionSimplifyPass::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text+0x2982): undefined reference to `llvm::Value::dump() const'
opt.cpp:(.text+0x2b5a): undefined reference to `llvm::Value::dump() const'
objs/opt.o: In function `ImproveMemoryOpsPass::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text+0x2d15): undefined reference to `llvm::Value::dump() const'
objs/opt.o:opt.cpp:(.text+0x7265): more undefined references to `llvm::Value::dump() const' follow
objs/opt.o: In function `DebugPass::runOnModule(llvm::Module&)':
opt.cpp:(.text+0xcd59): undefined reference to `llvm::Module::dump() const'
objs/opt.o: In function `PeepholePass::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text+0xcfa6): undefined reference to `llvm::Value::dump() const'
opt.cpp:(.text+0xdd30): undefined reference to `llvm::Value::dump() const'
objs/opt.o: In function `ReplaceStdlibShiftPass::runOnBasicBlock(llvm::BasicBlock&)':
opt.cpp:(.text+0xdecb): undefined reference to `llvm::Value::dump() const'
opt.cpp:(.text+0xe41d): undefined reference to `llvm::Value::dump() const'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dbabokin** [comment] 2019-02-22 18:20
Because you build with stock LLVM, instead of custom built LLVM. Please use alloy.py to build LLVM:
>alloy.py -b --version=5.0

LLVM 5.0 is recommended version to use with ISPC. LLVM 6.0, 7.0, and 8.0 are known to have multiple stability regressions.

**Comment by yurivict** [comment] 2019-02-22 20:09
> Because you build with stock LLVM, instead of custom built LLVM. Please use alloy.py to build LLVM:

This would be quite difficult to do, because my goal is to fix the FreeBSD port. This would require to create and maintain a flavor of the LLVM package just for ispc.

Did you try to contact the LLVM upstream about the stability problems, and did you ask them to adopt your patches that require a custom build?

**Comment by dbabokin** [comment] 2019-02-22 20:18
You don't need separate package. You need custom built LLVM only to be able to build ISPC. ISPC links all required LLVM libraries.

Stability and performance problems with LLVM 6.0+ are mostly due to interfacing of ISPC with LLVM - LLVM is constantly changing IR and optimizations, which (1) breaks some implicit contracts (2) introduce new LLVM bugs exposed by ISPC. In first case we fix the problem on our side, in second file issues and port the fixes back to stable LLVM version.

So we do work with LLVM and upstream the patches / report problems. But to build stable version of ISPC you need to use certain LLVM version with patches. Right now recommended version is 5.0.

The issue with dump() function is another aspect - LLVM needs to be built with extra flags to preserve dump() functions in LLVM. And we do need there dump() functions.

And again - you don't need a separate LLVM package, it should be built as part of ISPC build and its libraries are linked to final ISPC binary.

**Comment by yurivict** [comment] 2019-02-22 20:41
@dbabokin Thank you for this information.

Would adding ```--enable-keep-symbols``` be sufficient to build ```ispc```? I am trying to identify what would be the minimal overall change to ports system to get ```ispc``` to build, and I could probably add a flag or two to the stock llvmNN port for this.

**Comment by dbabokin** [comment] 2019-02-22 22:27
For LLVM 5.0 you need to pass -DLLVM_ENABLE_DUMP to compiler, i.e. you need to pass to cmake -DCMAKE_C_FLAGS=-DLLVM_ENABLE_DUMP -DCMAKE_CXX_FLAGS=-DLLVM_ENABLE_DUMP

For LLVM 6.0+ you need to pass -DLLVM_ENABLE_DUMP=ON to cmake.

But patches from llvm_patches are still required for a number of stability problems (for 5.0 you need to grep for *5_0* in patches name).

**Comment by junghans** [comment] 2019-02-26 18:00
@dbabokin it is the same problem as with packaging [flang](https://github.com/flang-compiler/flang), we cannot have multiple (patched differently) versions of llvm around in Fedora.

**Comment by yurivict** [comment] 2019-02-26 18:42
```dump()``` functions are considered to be debugging functionality by the LLVM project, and shouldn't be expected. Your use of ```dump()``` should be made optional.

**Comment by dbabokin** [comment] 2019-02-26 19:11
@junghans You don't need to have several versions of LLVM in Fedora. LLVM version that we need should be considered one of the build steps of ISPC. Once you've built ISPC, you don't need it around anymore. Could you explain why you consider it as another LLVM version *in Fedora*?

**Comment by dbabokin** [comment] 2019-02-26 19:14
@yurivict I know that LLVM considers dump() as optional functionality, but we consider it core functionality, so it's one of the reasons why we require certain LLVM build flavour. We'd like to have possibility to dump LLVM IR on user side when user encounters a bug.

**Comment by yurivict** [comment] 2019-02-26 19:32
The right solution is to have the LLVM project put all debug functionality into a separate library. Such library can be installed as a sub-package or as a separate package. This would eliminate the problem for everybody.

I'll make such suggestion to LLVM.

**Comment by yurivict** [comment] 2019-02-26 19:40
LLVM feature proposal: https://bugs.llvm.org/show_bug.cgi?id=40875

**Comment by dbabokin** [comment] 2019-02-26 19:40
I'm not sure that it's the right solution. dump() functions are spread out through the whole LLVM project, they are not located in some specific file. And changing that would be pain and harm maintainability.

Also, it's only part of the problem when building LLVM for ISPC. ISPC needs specific version of LLVM with specific set of patches. Otherwise ISPC will be broken from user prospective. For this reason LLVM should really be considered as part of LLVM build, not an external dependency.

**Comment by yurivict** [comment] 2019-02-26 21:32
@dbabokin You assume that LLVM builds easily everywhere. In reality it only builds easily on Linux, On BSDs it requires a set of patches and tweaks, which are all in the llvm port. Applying more patches on top of this and rebuilding leads to a heavy maintenance situation.

**Comment by jiapei100** [comment] 2020-05-08 23:20
@dbabokin 
What about LLVM 9 ???

**Comment by dbabokin** [comment] 2020-05-08 23:27
- The recommended version for ispc 1.13 and trunk is LLVM 10.0.
- LLVM 9.0 is also ok-ish, but LLVM 10.0 has a number of nice code generation improvements.
- As for using pre-built LLVM, we still don't recommend it, as it it doesn't have dumps/asserts enabled, which are very useful for debugging ispc itself when users encounter problems.
- The set of patches that we recommend for LLVM 10.0 is solely for avx512skx-i8x64 and avx512skx-i16x32 targets, which are enabled in trunk only.

**Comment by Martinfx** [comment] 2020-12-21 19:57
@dbabokin You have still issue with compile dump() function on FreeBSD. I dont need debug symbols for Release.

```
-- Build type not specified: Use Release by default.
-- Found LLVM LLVM_10_0
-- LLVM_CONFIG_EXECUTABLE: /usr/local/llvm10/bin/llvm-config
-- CLANG_EXECUTABLE: /usr/local/llvm10/bin/clang
-- CLANGPP_EXECUTABLE: /usr/local/llvm10/bin/clang++
-- LLVM_DIS_EXECUTABLE: /usr/local/llvm10/bin/llvm-dis
-- LLVM_AS_EXECUTABLE: /usr/local/llvm10/bin/llvm-as
-- FILE_CHECK_EXECUTABLE: /usr/local/llvm10/bin/FileCheck
-- Detected LLVM version: 10.0.1
CMake Warning at cmake/LLVMConfig.cmake:134 (message):
  LLVM was built without assertions enabled (-DLLVM_ENABLE_ASSERTIONS=OFF).
  This disables dumps, which are required for ISPC to be fully functional.
Call Stack (most recent call first):
  CMakeLists.txt:173 (include)


-- GIT_BINARY: /usr/local/bin/git
-- M4 macro processor: /usr/bin/m4
-- Found FLEX: /usr/bin/flex (found version "2.5.37") 
-- ISPC will be built with support of freebsd for arm
-- Enabling target: freebsd / armv7
-- Enabling target: freebsd / aarch64
-- Found Curses: /usr/lib/libcurses.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/maxfx/Documents/ispc
maxfx@ ~/D/ispc (master)> gmake -j6
[  1%] Generating builtins-dispatch.cpp
Scanning dependencies of target check_isa
[  1%] Generating builtins-dispatch-macos.cpp
[  2%] Generating lex.cpp
[  4%] Generating builtins-target-neon-i8x16-32bit-unix.cpp
[  4%] Generating builtins-target-neon-i8x16-64bit-unix.cpp
[  4%] Building CXX object CMakeFiles/check_isa.dir/check_isa.cpp.o
[  4%] Generating builtins-target-neon-i16x8-32bit-unix.cpp
[  5%] Linking CXX executable bin/check_isa
[  5%] Built target check_isa
[  6%] Generating builtins-target-neon-i16x8-64bit-unix.cpp
[  7%] Generating builtins-target-neon-i32x4-32bit-unix.cpp
[  8%] Generating builtins-target-neon-i32x4-64bit-unix.cpp
[  8%] Generating builtins-target-neon-i32x8-32bit-unix.cpp
[  9%] Generating builtins-target-neon-i32x8-64bit-unix.cpp
[ 10%] Generating builtins-cpp-32-freebsd-armv7.cpp
[ 11%] Generating builtins-cpp-64-freebsd-aarch64.cpp
[ 11%] Generating stdlib_mask1_ispc.cpp
[ 12%] Generating stdlib_mask8_ispc.cpp
[ 13%] Generating stdlib_mask16_ispc.cpp
[ 14%] Generating stdlib_mask32_ispc.cpp
[ 14%] Generating stdlib_mask64_ispc.cpp
[ 15%] Generating parse.cc
Scanning dependencies of target ispc
[ 16%] Building CXX object CMakeFiles/ispc.dir/builtins-dispatch.cpp.o
[ 16%] Building CXX object CMakeFiles/ispc.dir/builtins-dispatch-macos.cpp.o
[ 17%] Building CXX object CMakeFiles/ispc.dir/builtins-target-neon-i8x16-32bit-unix.cpp.o
[ 19%] Building CXX object CMakeFiles/ispc.dir/builtins-target-neon-i16x8-64bit-unix.cpp.o
[ 19%] Building CXX object CMakeFiles/ispc.dir/builtins-target-neon-i16x8-32bit-unix.cpp.o
[ 19%] Building CXX object CMakeFiles/ispc.dir/builtins-target-neon-i8x16-64bit-unix.cpp.o
[ 20%] Building CXX object CMakeFiles/ispc.dir/builtins-target-neon-i32x4-32bit-unix.cpp.o
[ 21%] Building CXX object CMakeFiles/ispc.dir/builtins-target-neon-i32x4-64bit-unix.cpp.o
[ 22%] Building CXX object CMakeFiles/ispc.dir/builtins-target-neon-i32x8-32bit-unix.cpp.o
[ 22%] Building CXX object CMakeFiles/ispc.dir/builtins-target-neon-i32x8-64bit-unix.cpp.o
[ 23%] Building CXX object CMakeFiles/ispc.dir/builtins-cpp-32-freebsd-armv7.cpp.o
[ 24%] Building CXX object CMakeFiles/ispc.dir/builtins-cpp-64-freebsd-aarch64.cpp.o
[ 24%] Building CXX object CMakeFiles/ispc.dir/stdlib_mask1_ispc.cpp.o
[ 25%] Building CXX object CMakeFiles/ispc.dir/stdlib_mask8_ispc.cpp.o
[ 26%] Building CXX object CMakeFiles/ispc.dir/stdlib_mask16_ispc.cpp.o
[ 27%] Building CXX object CMakeFiles/ispc.dir/stdlib_mask32_ispc.cpp.o
[ 27%] Building CXX object CMakeFiles/ispc.dir/stdlib_mask64_ispc.cpp.o
[ 28%] Building CXX object CMakeFiles/ispc.dir/parse.cc.o
[ 29%] Building CXX object CMakeFiles/ispc.dir/lex.cpp.o
[ 30%] Building CXX object CMakeFiles/ispc.dir/src/ast.cpp.o
[ 30%] Building CXX object CMakeFiles/ispc.dir/src/bitcode_lib.cpp.o
[ 31%] Building CXX object CMakeFiles/ispc.dir/src/builtins.cpp.o
[ 32%] Building CXX object CMakeFiles/ispc.dir/src/ctx.cpp.o
[ 33%] Building CXX object CMakeFiles/ispc.dir/src/decl.cpp.o
[ 33%] Building CXX object CMakeFiles/ispc.dir/src/expr.cpp.o
[ 34%] Building CXX object CMakeFiles/ispc.dir/src/func.cpp.o
[ 35%] Building CXX object CMakeFiles/ispc.dir/src/ispc.cpp.o
[ 36%] Building CXX object CMakeFiles/ispc.dir/src/llvmutil.cpp.o
[ 36%] Building CXX object CMakeFiles/ispc.dir/src/main.cpp.o
[ 37%] Building CXX object CMakeFiles/ispc.dir/src/module.cpp.o
[ 38%] Building CXX object CMakeFiles/ispc.dir/src/opt.cpp.o
[ 39%] Building CXX object CMakeFiles/ispc.dir/src/stmt.cpp.o
[ 39%] Building CXX object CMakeFiles/ispc.dir/src/sym.cpp.o
[ 40%] Building CXX object CMakeFiles/ispc.dir/src/target_enums.cpp.o
[ 41%] Building CXX object CMakeFiles/ispc.dir/src/target_registry.cpp.o
[ 42%] Building CXX object CMakeFiles/ispc.dir/src/type.cpp.o
[ 42%] Building CXX object CMakeFiles/ispc.dir/src/util.cpp.o
[ 43%] Linking CXX executable bin/ispc
ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by llvmutil.cpp
>>>               CMakeFiles/ispc.dir/src/llvmutil.cpp.o:(lDumpValue(llvm::Value*, std::__1::set<llvm::Value*, std::__1::less<llvm::Value*>, std::__1::allocator<llvm::Value*> >&))

ld: error: undefined symbol: llvm::Module::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(Optimize(llvm::Module*, int))

ld: error: undefined symbol: llvm::Module::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(Optimize(llvm::Module*, int))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(IntrinsicsOpt::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(IntrinsicsOpt::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(InstructionSimplifyPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(InstructionSimplifyPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(ImproveMemoryOpsPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(ImproveMemoryOpsPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(GatherCoalescePass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(GatherCoalescePass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(ReplacePseudoMemoryOpsPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(ReplacePseudoMemoryOpsPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(IsCompileTimeConstantPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(IsCompileTimeConstantPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Module::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(DebugPass::runOnModule(llvm::Module&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(PeepholePass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(PeepholePass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(ReplaceStdlibShiftPass::runOnBasicBlock(llvm::BasicBlock&))

ld: error: undefined symbol: llvm::Value::dump() const
>>> referenced by opt.cpp
>>>               CMakeFiles/ispc.dir/src/opt.cpp.o:(ReplaceStdlibShiftPass::runOnBasicBlock(llvm::BasicBlock&))
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/ispc.dir/build.make:752: bin/ispc] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:478: CMakeFiles/ispc.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2
```

**Comment by yurivict** [comment] 2020-12-21 20:22
@Martinfx If you build from the port ```devel/ispc``` this problem doesn't happen.

**Comment by dbabokin** [comment] 2020-12-21 20:37
If it doesn't work out of the box, you can use `-DISPC_NO_DUMPS=OFF` CMake switch.

**Comment by dbabokin** [comment] 2020-12-21 20:38
But again, if you are not using patch LLVM, your ISPC will be "broken". run `make check-all` to see all relevant fails.

**Comment by Martinfx** [comment] 2020-12-21 20:47
@dbabokin @yurivict  I am sorry. Thank you.

**Comment by nurmukhametov** [comment] 2023-10-25 12:19
It is resolved by https://github.com/ispc/ispc/pull/2412 that removed all usages of `dump`.

**Closed by nurmukhametov** 2023-10-25 12:19 UTC
