### ISSUE TITLE
Forward declaration of struct does not work

### ISSUE THREAD

**Issue by aganm** [ispc/ispc#2759] opened 2024-02-14 18:04 UTC
See this simple forward declaration of a struct, which compiles:
```C
typedef struct actual_vector2 vector2;

struct actual_vector2 {
	double x;
	double y;
};
```
But when I try to use it, I get compile errors:
```C
vector2 add(vector2 a, vector2 b) {
    vector2 c;
    c.x = a.x + b.x;
    c.y = a.y + b.y;
    return c;
}
```
> <source>:10:5: Error: Member operator "." can't be applied to 
>         declared but not defined struct type "varying struct actual_vector2". 
>     c.x = a.x + b.x;
>     ^^^

https://godbolt.org/z/PGP3Kefc9

Note how it suddenly works if you put the typedef right below the actual struct definition.

**Comment by aganm** [comment] 2024-02-14 18:05
Wait.. it works? Nevermind, I'm tired.

**Comment by aganm** [comment] 2024-02-15 07:46
Oh no.. it doesn't work. I needed more code to reproduce the bug. Forward declaration seems broken irrespective of bug #2351.

See this simple forward declaration of a struct, which compiles:
```C
typedef struct actual_vector2 vector2;

struct actual_vector2 {
	double x;
	double y;
};
```
But when I try to use it, I get a ton of compile errors:
```C
vector2 add(vector2 a, vector2 b) {
    vector2 c;
    c.x = a.x + b.x;
    c.y = a.y + b.y;
    return c;
}
```
> <source>:10:5: Error: Member operator "." can't be applied to 
>         declared but not defined struct type "varying struct actual_vector2". 
>     c.x = a.x + b.x;
>     ^^^

https://godbolt.org/z/PGP3Kefc9

**Comment by aneshlya** [comment] 2024-07-09 21:13
It is a duplicate of [#375](https://github.com/ispc/ispc/issues/375)

**Closed by aneshlya** 2024-07-09 21:13 UTC
Labels: Bugs
