### ISSUE TITLE
Varying reference function arguments

### ISSUE THREAD

**Issue by larsbohn** [ispc/ispc#2723] opened 2023-12-19 09:43 UTC
Consider the following code:

https://godbolt.org/z/1rrj4E467
```
struct S
{
    int member;
};

int expensive_function(S& varying_arg)
{
    return varying_arg.member;
}

void g()
{
    S s_array[10];        // Array of varying S
    int result;           // Varying result
    int i;

    for (i = 0; i < 10; i++)
    {
        if (s_array[i].member > 0)
        {
            break;
        }
    }

    result = expensive_function(s_array[i]); // Compile error
}
```

Can this be made working please?

Passing varyings as reference and thus accessing struct members through `.` instead of `->` is a huge boon to make the code consistent with other technologies and works perfectly when just calling directly with local variables.

Also note that the focus here is not to process a huge array where soa might be of interest, but just to be able to call a function in such a flexible way.

**Comment by aneshlya** [comment] 2024-01-24 19:19
Thanks for reporting the issue. This is a duplicate of #2430.

**Closed by aneshlya** 2024-01-24 19:19 UTC
