### ISSUE TITLE
Crash of ISPC with templated functions in the standard library

### ISSUE THREAD

**Issue by zephyr111** [ispc/ispc#2959] opened 2024-08-19 23:22 UTC
Hello,

There is apparently a bug happening in the tests of the PR #2958 causing ISPC to suddenly crash with the following message:

> /home/richard/Bureau/projects/ispc/src/module.cpp(1478): FATAL ERROR: Resulting module verification failed!

I can reproduce it on my machine. Strangely, it works well on my testing code. It apparently happens when there is a templated function in the `stdlib.ispc` and when this templated function is also called. Here is an example:

```
template <typename T> __declspec(safe) static inline void testing_func(T x) {}

__declspec(safe) static inline void caller_func(uniform float x) {
    return testing_func(x);
    // return testing_func<uniform float>(x);   // also fail
}
```

The command of the test causing the issue is the following:

> echo "" | ./bin/ispc -o - --target=avx2-i32x8 -E --emit-asm -

It crashes with all x86 targets the same way. 

-----

Note that with ARM ones (e.g. `neon-i32x4`), the error is different:

> stdlib.ispc:1496:48: Error: Undeclared symbol "__num_cores". Did you mean "num_cores"?

However, this problem happen even without changing any file.

Both issues happen with the latest commit so far.

**Comment by aneshlya** [comment] 2024-08-19 23:33
Template functions in stdlib are not fully supported yet but it should work after https://github.com/ispc/ispc/pull/2743 is merged.

**Comment by nurmukhametov** [comment] 2024-08-20 09:22
> echo "" | ./bin/ispc -o - --target=avx2-i32x8 -E --emit-asm -

This is a tricky test. It effectively forces codegeneration for the whole stdlib (for all functions it contains) that rarely happens in the wild. Let me review the cause when I will review PR #2958.

**Comment by nurmukhametov** [comment] 2024-08-29 16:57
> module.cpp(1478): FATAL ERROR: Resulting module verification failed!

It looks like the code creating a LLVM Function for a template instantiation creates incorrect LLVM IR like this:
```LLVM IR
$ opt -passes=verify t.ll
*.ll: error: invalid linkage for function declaration
declare internal float @_cbrtf___unf___unfunb(float, i1, <16 x i1>)
```

where `t.ll` is a dump of module immediately before module.cpp(1478).

**Comment by aneshlya** [comment] 2024-08-29 18:42
> It looks like the code creating a LLVM Function for a template instantiation creates incorrect LLVM IR like this:

Have you tried it on top of #2743? It works for me.

**Comment by nurmukhametov** [comment] 2024-08-30 13:59
With #2971, it is possible to see what is wrong with the module:
```bash
Global is external, but doesn't have external or weak linkage!
ptr @_cbrtf___unf___unfunb
Global is external, but doesn't have external or weak linkage!
ptr @_cbrtf_base___unf___unf
Global is external, but doesn't have external or weak linkage!
ptr @_cbrt_halley_iter___unf___unfunf
Global is external, but doesn't have external or weak linkage!
ptr @_cbrt_newton_iter___unf___unfunf
Global is external, but doesn't have external or weak linkage!
ptr @_cbrtf___vyf___vyfunb
Global is external, but doesn't have external or weak linkage!
ptr @_cbrtf_base___vyf___vyf
Global is external, but doesn't have external or weak linkage!
ptr @_cbrt_halley_iter___vyf___vyfvyf
Global is external, but doesn't have external or weak linkage!
ptr @_cbrt_newton_iter___vyf___vyfvyf
/home/oleshka/workspace/ispc/src/module.cpp(1529): FATAL ERROR: Resulting module verification failed!
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
/home/oleshka/workspace/ispc/src/main.cpp(403): FATAL ERROR: Unhandled signal sent to process; terminating.
```

> Have you tried it on top of #2743? It works for me.

Good, but anyway it is suspicious that declarations derived from templates look malformed for `llvm:verifier`.

**Comment by aneshlya** [comment] 2024-08-30 18:06
I realized where there problem is: we're setting linkage too early: https://github.com/ispc/ispc/blob/main/src/func.cpp#L1260. At `createLLVMFunction` we can create a function declaration with ExternalLinkage only. The logic regarding function linkage should be moved to the point where we produce IR for it. I'll create PR with a fix.

**Closed** 2024-09-04 19:41 UTC
