### ISSUE TITLE
Compile code on KNL crashed ISPC

### ISSUE THREAD

**Issue by shengfuintel** [ispc/ispc#1201] opened 2016-05-06 17:00 UTC
When I compile ISPC code on KNL, I got the following exception:

```
    Error: Assertion failed (ctx.cpp:2969): "llvmReturnType == 
    LLVMTypes::Int8VectorType". 
return *((const uniform bool *varying)(base + tls->mAttributeOffsets[key]));
```

I checked llvmReturnType is LLVMTypes::Int1VectorType, this is for bool. Is it because bool on KNL defined to the wrong type?

**Comment by dbabokin** [comment] 2016-05-13 14:23
I can reproduce it:
bool foo(bool *b) {
  return *b;
}

But I'm not sure what the correct fix is. I'm working on it.

**Comment by shengfuintel** [comment] 2016-05-13 16:08
How is bool in ISPC defined? Int8? Or int1?

Sent from my iPhone

On May 13, 2016, at 7:23 AM, Dmitry Babokin <notifications@github.com<mailto:notifications@github.com>> wrote:


I can reproduce it:
bool foo(bool *b) {
return *b;
}

But I'm not sure what the correct fix is. I'm working on it.

**Comment by ingowald** [comment] 2016-05-13 16:14
Probably depends on whether the bool is uniform or varying, as well as on ISA.
For varying bool, on SSE to AVX2 it _should_ actually be int32, on knx it should be int1, right? Uniform bool should be int8 either case.

**Comment by jbrodman** [comment] 2016-05-13 16:45
Depends on the platform.  If LLVM actually handled i1 properly, it'd be
that, but it doesn't.

**Comment by dbabokin** [comment] 2016-05-16 15:54
bool maps to i1 type for AVX512 targets. For SSE4-AVX2 targets bool width is matching "default type width" of the target (i.e. it's 8 for sse4-i8x16 target and 64 for avx2-i64x4, for example). Note, that this statement is about correspondence of ISPC and LLVM IR types. And LLVM IR types map correctly (and differently) to both registers and memory. i1 maps to byte in memory, while <16xi1> maps to 2 bytes. Looks like we just need to make gather work correctly with these types.

**Comment by shengfu** [comment] 2016-05-16 16:14
Thanks for the update, how soon can you have the fix?

**Comment by dbabokin** [comment] 2016-05-17 14:02
I think we'll have something for you later today.

General fix is to define bool as int8. This would enable full range of operations with varying bool, including gather/scatter. But performance implications of this are still need to be evaluated.

**Comment by dbabokin** [comment] 2016-05-17 19:36
We've prepared a version with bool mapping to int8. It's here at the moment https://github.com/Vsevolod-Livinskij/ispc/tree/knl_mask_i8

**Comment by dbabokin** [comment] 2022-01-25 08:35
The issue was fixed, closing.

**Closed by dbabokin** 2022-01-25 08:35 UTC
