### ISSUE TITLE
Masked stores used when setting shorter width registers in some cases

### ISSUE THREAD

**Issue by rkaric** [ispc/ispc#2719] opened 2023-12-15 13:44 UTC
Given the following code: https://godbolt.org/z/Kraa491fn

ISPC will operate on XMM registers up until the foreach() is encountered. Since the result is available in XMM0, it can safely perform an aligned/unaligned store using that register.

ISPC seems to broadcast to YMM0, load YMM1, mask store YMM0, and then clear the upper bits on YMM0.

**Comment by nurmukhametov** [comment] 2024-01-04 16:31
This looks like a duplicate of #2611.

**Comment by pbrubaker** [comment] 2024-04-25 01:37
Closing as duplicate of #2611.  This issue is mentioned in the other issue's thread.

**Closed by pbrubaker** 2024-04-25 01:37 UTC
