### ISSUE TITLE
Relax overloading limitiations

### ISSUE THREAD

**Issue by nurmukhametov** [ispc/ispc#3030] opened 2024-09-26 16:13 UTC
At the moment, it is not possible to overload ordinary function by a template one and vice versa.

For example, this code is not compiled with `Unable to find any matching overload for call to function "func".`.

```ispc
varying int32 func(varying int32 a, varying int32 b);
uniform int32 func(uniform int32 a, uniform int32 b);

template <typename T, uint N>
T<N> func(T<N> a, T<N> b)
{
    T<N> r;
    foreach (i = 0 ... N) {
        r[i] = func(a[i], b[i]);
    }
    return r;
}

uniform int<4> foo2(uniform int<4> a, uniform int<4> b) {
    return func<uniform int, 4>(a, b);
}
```

**Comment by aneshlya** [comment] 2024-09-26 16:29
Seems like a duplicate of https://github.com/ispc/ispc/issues/3015. It's not exactly about overloading. You may have `func` template and `func` function and overloading works fine in general case. Here the problematic line is  `r[i] = func(a[i], b[i]);` when we try to call function from template with the same name as template.

**Closed by aneshlya** 2024-09-26 16:29 UTC
Labels: Features, Templates
