### ISSUE TITLE
Multiple definition of __cast_mask_to_i32 since 1.18.0

### ISSUE THREAD

**Issue by mergian** [ispc/ispc#2320] opened 2022-05-09 09:12 UTC
When I try to link multiple ISPC object files I get multiple definitions of ```__cast_mask_to_i32``` since 1.18.0.

To reproduce the error:
```bash
echo "export void A() {}" > A.ispc
echo "export void B() {}" > B.ispc

ispc --pic --target avx512skx-x32 -o A.o A.ispc
ispc --pic --target avx512skx-x32 -o B.o B.ispc

nm A.o
nm B.o

gcc -shared A.o B.o -o error.so
```

Which produces following output:
```
0000000000000030 T A
0000000000000020 T A___
0000000000000000 T __cast_mask_to_i32

0000000000000030 T B
0000000000000020 T B___
0000000000000000 T __cast_mask_to_i32

B.o: In function `__cast_mask_to_i32':
B.ispc:(.text+0x0): multiple definition of `__cast_mask_to_i32'
A.o:A.ispc:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

This happens for the ```avx512skx-x32``` and ```avx512skx-x64``` targets.

**Comment by memcache0** [comment] 2022-05-19 00:17
I have reported this problem since ver 1.14.1, 1.14.0 or earlier versions are OK. See https://github.com/ispc/ispc/issues/2128

**Comment by pbrubaker** [comment] 2022-07-18 06:19
Closing as duplicate of #2128.

**Closed by pbrubaker** 2022-07-18 06:19 UTC
Labels: bugs
