### ISSUE TITLE
Compiler crashes on array field called 'd1'

### ISSUE THREAD

**Issue by tpyra** [ispc/ispc#2019] opened 2021-02-16 17:38 UTC
When in source code   there is reference to field named matches \.d[0-9]+   (i.e. 'd1') compiler crashes during compilation with an error message :

/builds/ispc/ispc/src/main.cpp(381): FATAL ERROR: Unhandled signal sent to process; terminating.
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
Aborted (core dumped)
--

Example sourcecode (it doesn't   matter is structure 'a' exist in any form - problem is in .d1 name)
https://godbolt.org/z/MxY6c4

**Comment by DeepakRajendrakumaran** [comment] 2021-02-18 00:21
The problem is ISPC frontend is interpreting '.d' as '0.0d0' -> 0.00. The lexer identifies the pattern as a fortran double. Will need to fix lexer/parser to identify this a field access or print error depending on case rather than crash.

**Comment by dbabokin** [comment] 2022-01-05 06:58
Fixed by #2123

**Closed by dbabokin** 2022-01-05 06:58 UTC
