### ISSUE TITLE
Compilation 'fatal error' when accessing undefined variable / function

### ISSUE THREAD

**Issue by petrsm** [ispc/ispc#2682] opened 2023-10-15 08:43 UTC
This may be by design, but I'll report it anyway. Accessing undefined variable / function does not produce
useful error message during compilation, but instead terminates with 'FATAL ERROR: unhandled signal sent to process' 
message.

ie. compiling this:

struct S_Test
{
 	uniform int m_Data;
};

void Test()
{
	S_Test tmp;

	tmp.m_Data  = 0; // ok
	tmp.m_Data2 = 0; // "FATAL ERROR: unhandled signal ..."
}

Occasionally, I make such a mistake and than it turns into detective work to find out the cause of compilation failing :)

**Comment by nurmukhametov** [comment] 2023-10-15 11:27
Which ISPC version do you use?

It is fixed in ISPC v1.21.0. (link: https://ispc.godbolt.org/z/bveKEEf5b)

Output:
```bash
<source>:11:1: Error: 'varying struct S_Test' has no member named 
        "m_Data2" 
tmp.m_Data2 = 0; // "FATAL ERROR: unhandled signal ..."
^^^^^^^^^^^

Compiler returned: 1
```

**Comment by petrsm** [comment] 2023-10-15 12:59
Sorry, I should have provided that info.

I am still using 1.20.0, because some other issue in 1.21.0 (https://github.com/orgs/ispc/projects/1pane=issue&itemId=36470214)

It is good to know, that it is fixed. I'll wait for 1.22. Thanks !

**Comment by nurmukhametov** [comment] 2023-10-16 09:45
I am closing this issue as this is duplicate of resolved https://github.com/ispc/ispc/issues/2514

**Closed by nurmukhametov** 2023-10-16 09:45 UTC
