### ISSUE TITLE
Stop shipping individual component libraries in clang-libs package

### ISSUE THREAD

**Issue by luyatshimbalanga** [ispc/ispc#2234] opened 2022-01-15 22:20 UTC
The individual component libraries will be removed from the clang-libs package in favor of libclang-cpp.so (which is already present in clang-libs). The component shared libraries enabled by the BUILD_SHARED=ON CMake option are not supported as a distribution configuration by the upstream project and only recommended for use by clang developers.[1]

The libclang-cpp.so shared object was added in clang 9.0 and now gives us an alternative shared library option that is supported by the upstream project and makes it possible for Fedora packages to stop using the component libraries.

This change will be made only in clang 10 and newer. The clang9.0 and older compatibility packages will keep the component libraries until those packages are retired.

[1] https://llvm.org/docs/CMake.html 

The patch below
[0001-Link-against-libclang-cpp.so.patch.txt](https://github.com/ispc/ispc/files/7875985/0001-Link-against-libclang-cpp.so.patch.txt)

Also see the [rationale done for Fedora 32](https://fedoraproject.org/wiki/Changes/Stop-Shipping-Individual-Component-Libraries-In-clang-lib-Package).

**Comment by pbrubaker** [comment] 2022-07-18 07:11
@dbabokin Have we applied this patch?

**Comment by nurmukhametov** [comment] 2023-03-22 11:40
It is a duplicate of https://github.com/ispc/ispc/issues/2104. It has been resolved by https://github.com/ispc/ispc/pull/2422

**Closed by nurmukhametov** 2023-03-22 11:40 UTC
Labels: Bugs, Building Compiler
