### ISSUE TITLE
Hang in CodeGen with lastest llvm trunk

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [ispc/ispc#1864] opened 2020-09-04 18:22 UTC
IR created by ISPC hangs when running Instruction selection CodeGen pass : Seem to be during this pass: (99) X86 DAG->DAG Instruction Selection on function (f_fu)

Hangs with following command : llc -mcpu=knl -mattr=+avx512f -opt-bisect-limit=-1 hang.ll -o hang.s

See attached IR file.

[Hang.zip](https://github.com/ispc/ispc/files/5176391/Hang.zip)

**Comment by DeepakRajendrakumaran** [comment] 2020-09-04 18:24
[Hang.zip](https://github.com/ispc/ispc/files/5176388/Hang.zip)

**Comment by dbabokin** [comment] 2020-09-17 00:14
The issue is fixed in LLVM, closing the issue.

**Closed by dbabokin** 2020-09-17 00:14 UTC
Labels: LLVM bug
