### ISSUE TITLE
Launching compiler without arguments and quitting via Ctrl-C leads to crash

### ISSUE THREAD

**Issue by didito** [ispc/ispc#1588] opened 2019-10-16 21:34 UTC
When I launch the compiler without arguments it seems to be waiting for input (which is kind of a weird default). When I try to exit via Ctrl+C then Windows Error Reporting (WER) kicks in because it crashed.

```
$>ispc.exe
Warning: No output file or header file name specified. Program will be compiled and warnings/errors will be issued, but no output will be generated.
Warning: No --target specified on command-line. Using default system target "avx2-i32x8".
C:\iusers\ispc_builder\ispc\src\main.cpp(357): FATAL ERROR: Unhandled signal sent to process; terminating.
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
<stdin>:1:1: Error: Premature end of file: syntax error, unexpected end of file.
```

version: v1.12.0, windows, 32bit, downloaded from here: https://ispc.github.io/downloads.html

```
$ >ispc.exe --version
Intel(r) SPMD Program Compiler (ispc), 1.12.0 (build date Aug 15 2019, LLVM 8.0.0)
Supported Visual Studio versions: Visual Studio 2015 and later.
```

**Comment by schwarzschild-radius** [comment] 2019-10-17 09:08
Please refer [this](https://github.com/ispc/ispc/issues/1411#issuecomment-457301000). It is an intended behaviour

**Comment by pbrubaker** [comment] 2019-10-17 17:04
I think waiting for standard input is fine, but crashing when interrupted/canceled is not.

**Comment by didito** [comment] 2019-10-17 23:31
As @pbrubaker said, crashing is definitely not fine.

The default of waiting for input is highly questionable. No other compiler has this behavior (Clang/LLVM, GCC). You need to pass "-" at the end for them to read standard input.
And interestingly, when you type `$ >ispc.exe -?` you get 

```
usage: ispc
    [ .. all the options]
    <file to compile or "-" for stdin>
```

**Comment by dbabokin** [comment] 2019-10-17 23:37
> No other compiler has this behavior
Disagree. Launch pyhton ;)

> The default of waiting for input is highly questionable.
Agree. This was Matt's experiment, when he envisioned ISPC to be more interactive tool. He wrote about it in his history of ISPC or some other blog posts about ISPC.

I vote to admitting that ISPC not an interactive tool and changing this behavior.

**Comment by pbrubaker** [comment] 2019-10-18 00:54
“I vote to admitting that ISPC not an interactive tool and changing this behavior.”

I concur.

**Comment by didito** [comment] 2019-10-18 01:07
> > No other compiler has this behavior
> 
> Disagree. Launch pyhton ;)

Well, Python is a compiler **and** interpreter and **REPL** (read input, eval, print, loop) is a cornerstone of the development workflow ;) Completely different to traditional work with C/C++ compilers emitting machine code. 

Again, not saying it is not a useful feature. Just questioning the default.

> > The default of waiting for input is highly questionable.
>  Agree. This was Matt's experiment, when he envisioned ISPC to be more interactive tool. He wrote about it in his history of ISPC or some other blog posts about ISPC.

Ok, did not know about this part of Matt's vision - I'll read up on it. But my claim is still that most people don't use it like that.

> I vote for admitting that ISPC not an interactive tool and changing this behavior.

I think that would be great 👍 Thank you!

**Comment by schwarzschild-radius** [comment] 2019-10-18 04:00
I am not getting the crashing behaviour from ispc 1.11.1 and 1.12.1. `llvm opt` has similar behaviour. So I think it is a normal as long as I can pipe input to ispc from the command line and get the output in stdout. 

If you changing planning to change the command line interface, I would recommend using [llvm command line library](https://llvm.org/docs/CommandLine.html). It is very simple and intuitive.

**Comment by pbrubaker** [comment] 2019-10-18 08:14
Are you trying on Windows, Linux or MacOS?  On Windows it triggers the OS
crash handler when canceled/interrupted but that may not replicate on
Linux/MacOS.

**Comment by schwarzschild-radius** [comment] 2019-10-18 08:15
I tried it on Linux (Ubuntu 18.04 LTS)

**Comment by didito** [comment] 2019-10-18 09:22
Exactly, not a Linux or MacOS issue. Happens on Windows only as indicated in my initial report.

**Comment by cloudhan** [comment] 2019-11-29 02:20
Maybe simply install a crash handler that only report back Ctrl-C is pressed.

**Comment by dbabokin** [comment] 2019-11-29 05:33
@cloudhan Looks like this feature is not used at all, while keeps confusing people.

**Comment by cloudhan** [comment] 2019-11-29 17:14
I vote for [SetInterruptFunction](https://llvm.org/doxygen/namespacellvm_1_1sys.html#a03a7c4c80c31a619c5e452314166401a)

**Comment by dbabokin** [comment] 2019-11-30 06:15
Current **default** behavior is confusing for most of the new users, so changing the default makes a lot of sense to me. Nevertheless, the ability to read from <stdin> is very useful in some scenarios and must be preserved. I'd like to do the following:
 - Require an input file to be specified.
 - To enable reading from <stdin> (which is default right now) user will need to specify "-" as input file.
 - Use SetInterruptFunction to avoid crash on Windows.

This follows what clang and gcc do. Does it make sense?

**Comment by cloudhan** [comment] 2019-12-02 01:53
I think it make sense. As long as it don't crash, I am fine with it.

**Comment by pbrubaker** [comment] 2020-04-21 05:48
Can this issue be closed?  This fix has been merged and this is the result with the current trunk build.

`C:\Users\PBRUBAKE>ispc
Error: No input file were specified. To read text from stdin use "-" as file name.`

**Comment by dbabokin** [comment] 2020-04-21 05:52
Indeed, it's time to close it.

**Closed by dbabokin** 2020-04-21 05:52 UTC
