### ISSUE TITLE
ispc 1.12.0 compiler crash

### ISSUE THREAD

**Issue by mikemccarty-vertex** [ispc/ispc#1595] opened 2019-10-30 16:16 UTC
I tried to simplify it as much as possible.  Commenting out the last line of `csClosestPoint()` avoids the crash.

Program also available at https://ispc.godbolt.org/z/5wyijf

```
struct Vec3f {
};

inline uniform float signedDist(uniform const Vec3f& pt) {
    return 0;
}

struct TriangleVerts
{
    Vec3f v0;
    Vec3f v1;
    Vec3f v2;
};

uniform TriangleVerts get_triangle_verts()
{
    uniform TriangleVerts tri;
    return tri;
}

void csClosestPoint()
{
    uniform TriangleVerts tri = get_triangle_verts();

    uniform const float d0 = signedDist(tri.v0);
}
```

**Comment by DeepakRajendrakumaran** [comment] 2019-10-30 22:07
The crash happens while running llvm's IPConstantpropogation pass. Can be reproduced with this -https://ispc.godbolt.org/z/45LBCg

**Comment by dbabokin** [comment] 2019-10-30 23:27
Please check if the bug is reproducible with LLVM 9.0 and trunk and file a bug against LLVM if it's not fixed yet.

**Comment by DeepakRajendrakumaran** [comment] 2019-10-30 23:33
It is reproducible with trunk(using opt trunk in the godbolt link above is one way to check).
 Holding off on filing a  bug for now as Craig is possibly adding a fix soon.

**Comment by dbabokin** [comment] 2019-10-31 00:07
Filing a bug against LLVM should do no harm and help Craig describe the problem in his patch. But I would say it's up to Craig to decide if he needs one.

**Comment by DeepakRajendrakumaran** [comment] 2019-10-31 00:14
https://bugs.llvm.org/show_bug.cgi?id=43857

**Comment by DeepakRajendrakumaran** [comment] 2019-10-31 16:49
Here is the change review - https://reviews.llvm.org/D69656 

Looks like the pass we are using is deprecated and we need to switch to -ipsccp: Interprocedural Sparse Conditional Constant Propagation

**Comment by dbabokin** [comment] 2019-11-21 05:58
@DeepakRajendrakumaran any update?

**Comment by DeepakRajendrakumaran** [comment] 2019-11-21 19:01
There are 2 parts to this-
1. The llvm fix to not crash with the current pass. This patch has already merged. I've tested it with 8.0 and it doesn't crash. Back-porting it to 8.0 is one option. This would be the short-term fix to stop the crash
2. Ideally, we need to look into using Interprocedural Sparse Conditional Constant Propagation instead.

**Comment by dbabokin** [comment] 2019-11-21 19:46
I suggest porting to 8.0 and 9.0 first and experiment with using Interprocedural Sparse Conditional Constant Propagation after that.

**Comment by DeepakRajendrakumaran** [comment] 2019-12-14 01:14
Fixed in trunk.

**Closed by DeepakRajendrakumaran** 2019-12-14 01:14 UTC
